"""added columns in player

Revision ID: 6e566ff404eb
Revises: fdb387da4098
Create Date: 2025-06-15 03:00:27.208480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e566ff404eb'
down_revision: Union[str, None] = 'fdb387da4098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.add_column('players', sa.Column('nick_name', sa.VARCHAR(), nullable=True))
    op.add_column('players', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.add_column('players', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('players', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'date')
    op.drop_column('players', 'gender')
    op.drop_column('players', 'email')
    op.drop_column('players', 'nick_name')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('nick_name', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('gender', sa.VARCHAR(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
