"""tpye_mon column update

Revision ID: f75ed7234fcb
Revises: e1e0394deed9
Create Date: 2025-06-16 00:29:45.370405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f75ed7234fcb'
down_revision: Union[str, None] = 'e1e0394deed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monsters', sa.Column('type_power', sa.String(), nullable=True))
    op.drop_column('monsters', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monsters', sa.Column('type', sa.VARCHAR(), nullable=True))
    op.drop_column('monsters', 'type_power')
    # ### end Alembic commands ###
